# Generated by Django 2.0.6 on 2020-03-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='statement',
            new_name='status',
        ),
    ]
